### ISSUE TITLE
Backgrouond-foreground Stutter

### ISSUE THREAD

**Issue by turnermm** [kvormweg/monochrome#2]
On one of my wikis, which has a lot going on, there is a "stutter" as the background gray is replaced by the foreground white:
http://www.youtube.com/watch?v=m59hCNIJVes

I've improved this using my tplmod plugin and setting the alt_background color to white (i.e. the color for the page background).  See this on the plugin page:
https://www.dokuwiki.org/plugin:tplmod#background_color_setting
And see this demonstration:
http://www.youtube.com/watch?v=7HJNd_4h2Rg

**Comment by turnermm** [comment]
This is the web site of the above video clips:

https://mturner.org/devel/

I like your template a great deal, it's quite elegant.

**Comment by kvormweg** [comment]
Looks to me like a slow server or network connection. The page is quite big. The white background CSS takes a while to load. This may be caused by preprocessing of the CSS files. You can also see in your videos that the sidebar lags. 

I use that template in a wiki farm at work and never had any problems with lagging content (on a fast network).

**Comment by turnermm** [comment]
I loaded the template into another dokuwiki on the same server and it ran without any problems. So I began a bit of an investigation and found the problem to be a plugin which I run to collect Internet traffic data.  Sadly, it's one of my own, Quickstats (not so quick it would seem).  Sorry to have bothered you.

**Comment by turnermm** [comment]
Made a major structural improvement to quickstats and the problem is entirely gone, without any workarounds.
   https://mturner.org/devel/
Thanks.
